spring:
  application:
    name: stock-payment-service
  config:
    import: file:env.properties

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_CONNECTION_URL}

  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event

app:
  jwt:
    secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 8051
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    root: DEBUG