spring:
  cloud:
    gateway:
      routes:
        - id: stock-auth-service
          uri: lb://stock-auth-service
          predicates:
            - Path=/auth/**

#        - id: identity-service
#          uri: lb://IDENTITY-SERVICE
#          predicates:
#            - Path=/auth/**

  application:
    name: stock-market-gateway
  config:
    import: file:env.properties

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8100
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: DEBUG